steps:
  - label: "Example Test"
    command: echo "Hello!"
  - wait
  - block: "Release"
    prompt: "Fill out the details for release"
    fields: 
      - text: "Release Name"
        key: "release-name"
        hint: "Think of a cool name for this release"
      - text: "Changelog"
        key: "release-notes"
        required: false
        hint: "List of what's changed in this release"
      - select: "Type"
        key: "release-type"
        default: "beta"
        options:
        - label: "Beta"
          value: "beta"
        - label: "Stable"
          value: "stable"
  - label: "Install NPM dependencies"
    command: npm install
    plugins:
      - docker#v1.0.0:
          image: node
          workdir: /app
